### ISSUE TITLE
Does this work with newest version of HA?

### ISSUE THREAD

**Issue by Martintygsen** [vash3d/nethassmo#2]
Hi Vash3d, 

Tried adding nethassmo through HACS but it doesn't show, when trying to add it as a custom repo, it says the Repository structure is not compliant. 

Might be me doing something wrong since I am new to HA, but I also saw the code wasn't updated for a couple of years so figured I would ask before doing much more. 

Happy new year! :)

**Comment by vash3d** [comment]
Hi Martin,
unfortunately I have not had time to maintain this release, so it is likely that there have been changes in the HACS protocols that cause the problem you describe.
In any case, the official integration for Netatmo is now much more complete and functional and allows you to perform the same functions and automations for which I developed nethassmo. I use it myself. 

The only thing you can do more with my app is to disable the monitoring (manually or through an automation).  That's the only reason I still use it.
If you want, you can try to install it by copying the files directly into the apps folder of appdaemon on your system instead of installing it from HACS.
Hope this helps.

**Comment by Martintygsen** [comment]
Thank you very much for a fast response :) I will try go with the official integration and see if that solves my needs. It probably will - Just need to figure out how it works. :)
